spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    database-platform:
    hibernate:
      ddl-auto:
    show-sql: true
  data:
    redis:
      host:
      port: