spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: yeji
    password: 0708
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    key: "28bKroKcpGNVZC2JW5QEops4QoY2fWobjtqn/bOZ6dw="